version: '2'

services:
 git: 
  container_name: gitlab
  image: gitlab/gitlab-ce
  volumes:
    - "/data/gitlab/:/gitlab/data/"

 ci:
  container_name: jenkins
  image: jenkins
  volumes:
    - "/data/jenkins/:/jenkins/data/"

 db: 
  container_name: db
  image: mariadb
  ports:
    - "3306:3306"
  volumes:
    - "/data/mysql/:/var/lib/mysql/"
  env_file:
    - ./service.env 
  
 cache:
  container_name: cache
  image: redis

 api:
  container_name: api
  image: webdevops/php-nginx
  volumes:
    - "/opt/production/api/:/opt/production/"
  ports:
    - "83:80"
  depends_on:
   - db
   - cache
  env_file:
    - ./service.env 
  links:
   - db:database
   - cache

 backend:
  container_name: backend
  image: webdevops/php-nginx
  volumes:
    - "/opt/production/backend/:/opt/production/"
  ports:
    - "82:80"
  depends_on:
   - api
  env_file:
    - ./service.env 

 frontend:
  container_name: frontend
  image: webdevops/php-nginx
  volumes:
    - "/opt/production/frontend/:/opt/production/"
  ports:
    - "81:80"
  depends_on:
   - api
  env_file:
    - ./service.env 

 web:
  container_name: web
  image: nginx
  ports:
    - "80:80"
  depends_on:
   - frontend
   - backend




